// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthRequest {
    /// Current is 0x
    #[prost(fixed32, tag = "1")]
    pub protocol_version: u32,
    /// This token is used for authentication
    #[prost(string, tag = "2")]
    pub auth_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub broker_credential: ::prost::alloc::string::String,
}
