// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthRequest {
    /// This token is used for authentication
    #[prost(string, tag = "1")]
    pub auth_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    /// Optional additional data for authentication
    #[prost(btree_map = "string, string", tag = "5")]
    pub extra: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthResponse {
    /// 0 = OK, any other value = error
    #[prost(int32, tag = "1")]
    pub status_code: i32,
    /// Textual explanation if there's an error
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
